=== FilipLand/3er-Eval/3er eval/src/LenguajeDeMarcas/EjercicioQuiado/cuento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
    <xs:documentation>
        <titulo>Ejemplo de repaso Cuentos</titulo>
        <modulo>Lenguaje de Marcas y sistemas de gestion de la informaci√≥n</modulo>
        <fecha_creacion>2024-04-10</fecha_creacion>
        <autor>Filip Mlynarczyk</autor>
    </xs:documentation>
</xs:annotation>
<!--elementos complejos -->
<!--elemento raiz cunto (personajes, trama, etiqueta)-->
    <xs:element name="cuento">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="personajes"/>
                <xs:element ref="trama"/>
                <xs:element ref="etiqueta" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="cod" use="required"/>
            <xs:attribute ref="titulo" use="required"/>
            <xs:attribute ref="genero" use="optional"/>
        </xs:complexType>
    </xs:element>

<!-- elemento personajes (personaje+) -->
    <xs:element name="personajes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="personaje" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
<!-- elemto personaje(nombre, genero, descripcion?)-->
<xs:element name="personaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="genero"/>
                <xs:element ref="descripcion" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute ref="tipo" default="principal"/>
        </xs:complexType>
        </xs:element>

        <!--elemento etiqueta-->
    <xs:element name="etiqueta">
        <xs:complexType>
            <xs:attribute ref="nombre" use="required"/>
        </xs:complexType>
    </xs:element>

        <!-- Elementos simples -->
        <!-- Elementos simples de cuento-->
        <xs:element name="trama" type="xs:string"/>
        <!-- elementos simples de personaje -->
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="genero">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="masculino|femenino|neutro"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="descripcion" type="xs:string"/>

        <!-- atributos -->
        <!-- Atributos de cuento -->
        <xs:attribute name="cod">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]\d{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="titulo" type="xs:string"/>
        <xs:attribute name="genero">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="infantil"/>
                    <xs:enumeration value="fantasia"/>
                    <xs:enumeration value="terror"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <!-- atributos de personaje -->
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="tipo">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="principal"/>
                    <xs:enumeration value="secundario"/>
                    <xs:enumeration value="antagonista"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
            <!-- atributo de etiqueta -->
            <xs:attribute name="nombre" type="xs:string"/> 
</xs:schema>

=== FilipLand/3er-Eval/3er eval/src/LenguajeDeMarcas/EjercicioQuiado/cuento1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuento>
<cuento cod="A01" titulo="La Cenicienta" genero="infantil"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cuento.xsd">
    <personajes>
        <personaje id="A1" tipo="principal">
            <nombre> Cenicienta </nombre>
            <genero>femenino</genero>
            <descripcion> Una joven trabajadora y bondadosa</descripcion>
        </personaje>
        <personaje id="A2" tipo="secundario">
            <nombre> madrastra </nombre>
            <genero>femenino</genero>
            <descripcion> Una mujer cruel y ambiciosa</descripcion>
        </personaje>
        <personaje id="A3" tipo="principal">
            <nombre> El Principe </nombre>
            <genero>masculino</genero>
            <descripcion> Un joven apuesto y formal</descripcion>
        </personaje>
    </personajes>
    <trama> La historia de Cenicienta, una joven maltratada por su 
        madrastra y sus hermanastras, y su viaje para encontrar su
        verdadero amor con la ayuda de la hada madrina. 
    </trama>
    <etiqueta nombre="amor"></etiqueta>
    <etiqueta nombre="superacion"></etiqueta>
</cuento>
